version: '3.5'

services:
  db_auth:
    container_name: tacoProject
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:alpine3.18